rm -rf build devel
catkin_make arm_control_generate_messages
catkin_make rm_msgs_generate_messages
catkin_make arm_control
catkin_make behavior_module_generate_messages
catkin_make perform_module_generate_messages
catkin_make