pip2 install pathlib jieba
rm -rf build devel
catkin_make arm_control_generate_messages
catkin_make rm_msgs_generate_messages
catkin_make arm_control
catkin_make behavior_module_generate_messages
catkin_make perform_module_generate_messages
catkin_make -DCATKIN_WHITELIST_PACKAGES="social_msg"
catkin_make -DCATKIN_WHITELIST_PACKAGES=""
# catkin_make